"""Detects exported files generated by SAP."""
from __future__ import annotations

import time
from pathlib import Path

from app.sap.exceptions import SapExportTimeoutError


class ExportFileWatcher:
    """Watches a directory for newly created or updated files."""

    def __init__(self, directory: Path, file_glob: str, timeout_seconds: int, poll_seconds: float = 1.0):
        self._directory = Path(directory).expanduser()
        self._file_glob = file_glob
        self._timeout_seconds = timeout_seconds
        self._poll_seconds = poll_seconds

    def snapshot(self) -> dict[Path, float]:
        """Returns current files and their mtime."""
        if not self._directory.exists():
            self._directory.mkdir(parents=True, exist_ok=True)

        snapshot: dict[Path, float] = {}
        for path in self._directory.glob(self._file_glob):
            try:
                resolved = path.resolve()
                snapshot[resolved] = resolved.stat().st_mtime
            except OSError:
                continue
        return snapshot

    def wait_for_export(self, baseline: dict[Path, float], execution_started_epoch: float) -> Path:
        """Waits for a new or modified file after execution start timestamp."""
        deadline = time.monotonic() + self._timeout_seconds
        candidate: Path | None = None
        candidate_mtime = -1.0

        while time.monotonic() < deadline:
            for path in self._directory.glob(self._file_glob):
                try:
                    resolved = path.resolve()
                    mtime = resolved.stat().st_mtime
                except OSError:
                    continue

                previous_mtime = baseline.get(resolved)
                is_new = previous_mtime is None
                is_updated = previous_mtime is not None and mtime > previous_mtime + 1e-6
                is_after_execution = mtime >= execution_started_epoch - 1.0

                if (is_new or is_updated) and is_after_execution and mtime > candidate_mtime:
                    candidate = resolved
                    candidate_mtime = mtime

            if candidate is not None:
                return candidate

            time.sleep(self._poll_seconds)

        raise SapExportTimeoutError(
            "Nao foi possivel detectar o arquivo exportado no tempo limite. "
            f"Diretorio monitorado: {self._directory} | padrao: {self._file_glob}"
        )
